### PR TITLE
Add vignette plus re-ran packagedown and fixed minor errors on readme

### LINKED ISSUE #53: use vignette package-wide documentation

### PR DESCRIPTION
**Pull request by sweber15**
closes #53

### CODE REVIEW

**Review by v5y8 — APPROVED** [review]
looks fine

**Comment by sgauravm** [comment]
Can you please make the same changes as made in README.md for function description in eda.R function description

**Comment by sweber15** [comment]
> Can you please make the same changes as made in README.md for function description in eda.R function description

I tried to make them in line, but it didn't make sense to have the inputs in the docstring explanation because the parameters and types were already in the docstring. If you agree, please approve and merge.

**Review by marvinmin — APPROVED** [review]
looks good

**Review by sgauravm — APPROVED** [review]
Looks good.Thanks for the changes

**Pull request merged**
