### PR TITLE
fixed a missing plot in readme and added one-line descriptions

### LINKED ISSUE #49: Revisit Tests and Documentation
Make sure all tests pass:

- You may ask other team members to examine your test cases and add new ones, if appropriate.
- At each step, check the build status and read GitHub Actions logs.
- examine docstrings of your functions
- examine whether one-line descriptions of your unit test functions make sense

### PR DESCRIPTION
**Pull request by marvinmin**
close #49

### CODE REVIEW

**Review by v5y8 — APPROVED** [review]
looks good. can merge

**Review by sweber15 — COMMENTED** [review]
Two comments if you aren't able to do I can make another PR:

1. Should we update the dependancy with the one you needed to add to get the CI working?

2. I put the link to the website on the description of the repo at the top, but we should probably link the Vignette in the example.

**Comment by marvinmin** [comment]
> Two comments if you aren't able to do I can make another PR:
> 
> 1. Should we update the dependancy with the one you needed to add to get the CI working?
> 2. I put the link to the website on the description of the repo at the top, but we should probably link the Vignette in the example.

1. Which dependency?
2. I can add the link in the example.

**Comment by sweber15** [comment]
> > Two comments if you aren't able to do I can make another PR:
> > 
> > 1. Should we update the dependency with the one you needed to add to get the CI working?
> > 2. I put the link to the website on the description of the repo at the top, but we should probably link the Vignette in the example.
> 
> 1. Which dependency?
> 2. I can add the link in the example.

1. vctrs,
    lifecycle,
    pillar

**Comment by marvinmin** [comment]
> > > Two comments if you aren't able to do I can make another PR:
> > > 
> > > 1. Should we update the dependency with the one you needed to add to get the CI working?
> > > 2. I put the link to the website on the description of the repo at the top, but we should probably link the Vignette in the example.
> > 
> > 
> > 
> > 1. Which dependency?
> > 2. I can add the link in the example.
> 
> 1. vctrs,
>    lifecycle,
>    pillar

Oh, right, I'll add them. Thanks.

**Comment by marvinmin** [comment]
> Two comments if you aren't able to do I can make another PR:
> 
> 1. Should we update the dependancy with the one you needed to add to get the CI working?
> 2. I put the link to the website on the description of the repo at the top, but we should probably link the Vignette in the example.

The link to the Vignette is the one you put at the top of the repo?

**Comment by sweber15** [comment]
> > Two comments if you aren't able to do I can make another PR:
> > 
> > 1. Should we update the dependancy with the one you needed to add to get the CI working?
> > 2. I put the link to the website on the description of the repo at the top, but we should probably link the Vignette in the example.
> 
> The link to the Vignette is the one you put at the top of the repo?

That is the link to the website. The Vignette is hidden there as https://ubc-mds.github.io/edar/articles/edar-vignette.html

**Comment by marvinmin** [comment]
> > > Two comments if you aren't able to do I can make another PR:
> > > 
> > > 1. Should we update the dependancy with the one you needed to add to get the CI working?
> > > 2. I put the link to the website on the description of the repo at the top, but we should probably link the Vignette in the example.
> > 
> > 
> > The link to the Vignette is the one you put at the top of the repo?
> 
> That is the link to the website. The Vignette is hidden there as https://ubc-mds.github.io/edar/articles/edar-vignette.html

added. And I also added another numeric column in the example to make the correlation plot look a little bit nicer.

**Review by sweber15 — APPROVED** [review]
It looks good!

**Pull request merged**
